### ISSUE TITLE
Slack link from README not working

### ISSUE THREAD

**Issue by shalom-aviv** [meditohq/medito-app#214]
Slack link from README not working

https://meditofoundation.slack.com/join/shared_invite/zt-f0viisyt-VdJ7ygqNHt9sIeGzZiatlQ#/shared-invite-legacy/erro

<img width="649" alt="Screenshot 2021-10-22 at 15 26 51" src="https://user-images.githubusercontent.com/78256107/138453427-f31c1102-2bdb-4317-9e5f-4a72988af105.png">

**Comment by michaelcspeed** [comment]
We are almost reaching our user limit on Slack so we have disabled the link for now :)

**Comment by blipp** [comment]
Hi @scouech, @michaelcspeed – I also came here because I found the not-working Slack invite link in the README of this repo and on the website under https://meditofoundation.org/contact

Would it be an option for you to remove the invite link, to avoid people over and over again asking about it? :) I say that because I also sent an email to hi@ some time ago about the Slack invite link and did not get an answer.

Related closed issue: #209 

Thanks for you work on the Medito app. I just today learned that it is also open source, that's really great :) I started a monthly donation a couple of days ago to support the foundation.

**Comment by blipp** [comment]
I see you actually removed one occurrence of the Slack link with commit https://github.com/meditohq/medito-app/commit/75635ec60f34b89717d5cfb930d51d66d82d36b2 :)

The following is still in the README:

```
You will need an API key to build the project.

To request one, join the #dev channel on [slack](https://join.slack.com/t/meditofoundation/shared_invite/zt-f0viisyt-VdJ7ygqNHt9sIeGzZiatlQ) and reply to the slackbot questions.
```

(and then the one on the website on /contact)

**Comment by blipp** [comment]
It also appears here on the wiki: https://github.com/meditohq/medito-app/wiki
