### ISSUE TITLE
[BUG] Version 3.0 does not work without Google Play Services on Android

### ISSUE THREAD

**Issue by parcelcat** [meditohq/medito-app#581]
Version 3.0 does not work without Google Play Services on Android. Instead, the app displays a blank screen. This issue makes the app unusable on Android-based devices that do not include Google Play Services, including Amazon's Fire tablets, devices sold in places where Google is banned (China), and privacy-oriented devices that exclude Google services.

This issue occurs because the app refuses to load any content if Firebase Cloud Messaging (implemented in #373) fails to generate a registration token for the device. To fix the issue and enable all Android devices to access Medito, the app should continue to show content even if FCM is unavailable. (For devices without Google Play Services, the app should not prompt the user to allow push notifications or to create an account, since these features are currently implemented in a way that depends on FCM.)

**Comment by scouech** [comment]
Thanks @parcelcat . Added it to the backlog!

**Comment by GiraffeCubed** [comment]
I've run in to this issue today after clearing Play Services data (had to in order to fix a Google Wallet issue). Can't access the app at all unfortunately, stuck on the initial Medito 'M' logo and the app doesn't advance. I guess for me this will resolve itself eventually with a new token since I still have Google Play Services, but this implementation would prevent this from being an issue too

**Comment by TeetotalingTom** [comment]
Has any progress been made with this issue? I've been using Medito V2 on an Android device that does not support Google Play Services, but as said version will no longer be supported from December the 19th, it looks as though it will soon be impossible for me to use any version of Medito at all.

**Comment by scouech** [comment]
@TeetotalingTom we don't have the resources at the moment to provide a fix. In the meantime you can download the APK from a place like APK Pure
https://apkpure.com/nl/medito-meditation-sleep/meditofoundation.medito/download
Hope it helps

**Comment by TeetotalingTom** [comment]
@scouech Thanks for commenting. However, for me is not that I cannot find V3.0.12, but that it does not run on my phone in absence of Google Play Services (GPS). Most users of degoogled Android operating systems know how to find desired apps, so the issue here is the app requiring GPS to work.
If currently no resources are available to implement parcelcat's suggestion, is it possible to postpone the date V2.0.48 will be taken offline (instead of today)? In that case Android users without GPS will be able to use the old version until a new version is available for them too.

**Comment by scouech** [comment]
@TeetotalingTom if you want to create a PR with the fix it would be welcome. We can delay it till maximum next Tuesday if you want to work on it before then. We can't really keep things running as it's directly affecting our finances. Let me know by tomorrow Wednesday 20th CET otherwise we will look at it when we can and shut down v2 tomorrow. Cheers

**Comment by TeetotalingTom** [comment]
@scouech I'm afraid I don't have the technical knowledge to implement the solution proposed by parcelcat, so please do not postpone the shutdown because of me. Let me state, however, that I started using Medito because Insight Timer required GPS, whereas Medito V2.0.48 did not. Looking at the number of thumbs up for the original post here, this might have brought many users to Medito at the time.
Maybe @parcelcat has the opportunity to implement the solution in the near future? I would gladly start using V3 once it would be available without GPS.

**Comment by scouech** [comment]
Thanks @TeetotalingTom . 
I've put ticket to be next. I can't guarantee when it will be picked up. Hopefully before the end of the year. 
In the meantime you can use the website https://meditofoundation.org/meditations we have some content on there. We will retire v2 today. Keep an eye on this ticket and will keep you updated with the progress.

**Comment by TeetotalingTom** [comment]
@scouech Thanks for your reply. I appreciate the website link and in the meantime I've dusted off an old device to keep using the app until a release that doesn't depend on GPS. I'll keep my eyes on the ticket too. Best of luck with picking it up.

**Comment by TeetotalingTom** [comment]
Hi @scouech is there a timeline for updating the app in the Play Store? It seems Michael Speed closed this issue a month ago, but the last app update was right before, so the app is still unusable for me. I could learn to build a .apk from this repo, but if an app update is scheduled soon, that would save me a lot of effort.

**Comment by parcelcat** [comment]
@TeetotalingTom It looks like the app was updated in the Play Store on February 11. I can confirm that the issue has been resolved in version 3.0.22.
