### ISSUE TITLE
Background sound fade does not work

### ISSUE THREAD

**Issue by scouech** [meditohq/medito-app#603]
The background sound should fade when reaching the end of a track. It stopped working. I've tested at least on iOS. Could you look into it? Cheers

- [x] Background sound fades on iOS
- [x] Background sound fades on Android

**Comment by osamaasifoak** [comment]
@scouech checked it on my end. It's working fine.

**Comment by foss-** [comment]
While it is nice that this works for your @osamaasifoak it does not work for me in
Android ArrowOS 13.1
Medito 3.0.11

Steps to reproduce:

1. open Meditation timer > 3 mins
2. hit play
3. when time is up, there is no fade and audio abruptly stops

**Currently**
The abrupt audio stop is fairly rough, especially after longer times trying to relax or meditate.

**Expected**
Sound should fade softly.

Some work on this happened recently in https://github.com/meditohq/medito-app/pull/564 but without a milestone tag it is hard to tell, in which version of the app the fix should be expected.

Edit to add that fade just worked as expected so this isssue is a bit more involved since sadly it isn't 100 % reproducible.

**Comment by scouech** [comment]
@foss- we don't support ArrowOS at the moment. I will leave the ticket open if anyone else wants to pick it up. We don't have the resources at the moment to pick it up. 
If more people experience the issue we will pick it up. 
Cheers

**Comment by foss-** [comment]
Understood and feel free to close. ArrowOS is close to AOSP so wondering if the issue is limited to it or maybe also happens on stock Android.

**Comment by kevinsivic** [comment]
I just experienced this on a stock pixel 6a so it's not limited to AOSP. 

It might be interesting to note that I added the background sound after starting the meditation. I'll play around with it some more and add details if I can reliably reproduce it.

**Comment by kevinsivic** [comment]
I did a bit more debugging and it seems that the background fade works when the screen is on but does not work if the screen is off or the app is in the background when the fade period is supposed to trigger.

Steps to reproduce:
1. open Meditation timer > 3 mins
2. hit play
3. Skip to 15 seconds remaining
4. Send app to background or turn off screen

Expected Behavior:
Background audio fades out over the last 5 seconds of the timer.

Actual Behavior:
Background audio cuts off abruptly when timer ends.

It looks like `handleFadeAtEnd` is called in three places, twice in `duration_indicator_widget.dart` and once in `player_buttons_widget.dart`. All of these calls only happen if the widget is active. It seems like something other than a widget needs to watch the audio player to see when fade should be triggered.

**Comment by foss-** [comment]
Can confirm your finding, thanks for taking the time to further investigate this issue.
