### ISSUE TITLE
[Suggestion] Advertise This GitHub in the App

### ISSUE THREAD

**Issue by OkyDooky** [meditohq/medito-app#693]
I understand the need for asking for funds to support the services you host, but I feel it is a missed opportunity to not also regularly remind users of this page and also link to it in the three-dot menu.

It would help in attracting more people who could help contribute bug fixes and extra features, voluntarily. This would speed up development without requiring you to hire more developers (while also not excluding that option).

I had been using the app for over two years before I discovered that this app was already open source and hosted here. And I'm sure I'm not the only one.

**Comment by Lionelf329** [comment]
I'm not sure how useful that would be at this point, because they haven't updated the repo in months and haven't responded on email or discord when I asked about it. I guess it's worth tagging them in a github issue just to cover all the bases, @michaelcspeed any chance we could get the updated code in here?
