### ISSUE TITLE
Developer Documentation

### ISSUE THREAD

**Issue by devtayls** [meditohq/medito-app#95]
I'm new to flutter development and don't really know how to build the project. 

We should beef up the contribution guide to walk people through initializing and running the project. 

A good place for this guide would be README.MD

**Comment by scouech** [comment]
hey @devtayls. What would help? More like a step by step guide? Do you have ideas?

**Comment by paulgoetze** [comment]
First of all: Thanks for your great work here and the Medito app! :green_heart: 

I was also trying to set it up for development and ran into issues (on Ubuntu 21.10).

`flutter --version` gives me the following setup:

```
Flutter 2.10.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 097d3313d8 (vor 6 Tagen) • 2022-02-18 19:33:08 -0600
Engine • revision a83ed0e5e3
Tools • Dart 2.16.1 • DevTools 2.9.2
``` 
 
After I found that I needed to create a `network/auth.dart` file and put some random values, 
I was trying to build the project in VS Code with the flutter emulator (android_x86).

<details>
  <summary>
     <b>Failure due to android:name="io.flutter.app.FutterApplication"</b>
  </summary>
<pre>
<code>  
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Warning
──────────────────────────────────────────────────────────────────────────────
Your Flutter application is created using an older version of the Android
embedding. It is being deprecated in favor of Android embedding v2. Follow the
steps at
https://flutter.dev/go/android-project-migration
to migrate your project. You may also pass the --ignore-deprecation flag to
ignore this check and continue with the deprecated v1 embedding. However,
the v1 Android embedding will be removed in future versions of Flutter.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
The detected reason was:
  /home/paul/projects/medito-app/android/app/src/main/AndroidManifest.xml uses `android:name="io.flutter.app.FutterApplication"`
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Build failed due to use of deprecated Android v1 embedding.
Exited (1)
</code>
</pre>
</details>

So, as recommended, I changed this to `"${applicationName}"` instead, which fixed the warning.

When I tried to build again it failed and raised a couple of warnings: 

<details>
  <summary>
     <b>Failure due to too SDK version < 31</b>
  </summary>
<pre>
<code>  
Launching lib/main.dart on AOSP on IA Emulator in debug mode...
lib/main.dart:1
The app could not be configured for release signing. In app purchases will not be testable. See `example/README.md` for more info and instructions.
Warning: The plugin firebase_core requires Android SDK version 31.
Warning: The plugin package_info_plus requires Android SDK version 31.
Warning: The plugin path_provider_android requires Android SDK version 31.
Warning: The plugin sentry_flutter requires Android SDK version 31.
Warning: The plugin shared_preferences_android requires Android SDK version 31.
Warning: The plugin url_launcher_android requires Android SDK version 31.
Warning: The plugin video_player_android requires Android SDK version 31.
Warning: The plugin webview_flutter_android requires Android SDK version 31.
One or more plugins require a higher Android SDK version.
Fix this issue by adding the following to /home/paul/projects/medito-app/android/app/build.gradle:
android {
  compileSdkVersion 31
  ...
}
</code>
</pre>
</details>

So I put the compileSdkVersion & targetSdkVersion to 31, which fixed these warnings, 
but left me with some other errors for the `audio_service` package:

<details>
  <summary>
     <b>Failure due to missing methods for the class 'MethodChannel'</b>
  </summary>
<pre>
<code>  
: Error: The method 'setMockMethodCallHandler' isn't defined for the class 'MethodChannel'.
../…/lib/audio_service.dart:675
- 'MethodChannel' is from 'package:flutter/src/services/platform_channel.dart' ('../../snap/flutter/common/flutter/packages/flutter/lib/src/services/platform_channel.dart').
package:flutter/…/services/platform_channel.dart:1
Try correcting the name to the name of an existing method, or defining a method named 'setMockMethodCallHandler'.
              .setMockMethodCallHandler(handler);
               ^^^^^^^^^^^^^^^^^^^^^^^^
: Error: The method 'setMockMethodCallHandler' isn't defined for the class 'MethodChannel'.
../…/lib/audio_service.dart:1267
- 'MethodChannel' is from 'package:flutter/src/services/platform_channel.dart' ('../../snap/flutter/common/flutter/packages/flutter/lib/src/services/platform_channel.dart').
package:flutter/…/services/platform_channel.dart:1
Try correcting the name to the name of an existing method, or defining a method named 'setMockMethodCallHandler'.
          .setMockMethodCallHandler(handler);
           ^^^^^^^^^^^^^^^^^^^^^^^^
3

FAILURE: Build failed with an exception.

* Where:
Script '/home/paul/snap/flutter/common/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1102

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/home/paul/snap/flutter/common/flutter/bin/flutter'' finished with non-zero exit value 1
</code>
</pre>
</details>

I tried updating `audio_service` to `^0.18.0`, which seemed to have changed quite some APIs:

<details>
  <summary>
     <b>Failure due to API changes in audio_service 0.18</b>
  </summary>
<pre>
<code>  
flutter run --ignore-deprecation                                                                                                         64 ↵
Using hardware rendering with device AOSP on IA Emulator. If you notice graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on AOSP on IA Emulator in debug mode...
The app could not be configured for release signing. In app purchases will not be testable. See `example/README.md` for more info and instructions.
lib/network/downloads/downloads_bloc.dart:46:30: Error: Member not found: 'MediaItem.fromJson'.
        var file = MediaItem.fromJson(jsonDecode(element));
                             ^^^^^^^^
lib/network/downloads/downloads_bloc.dart:80:45: Error: Member not found: 'MediaItem.fromJson'.
    list.removeWhere((element) => MediaItem.fromJson(jsonDecode(element)).id == mediaFile.id);
                                            ^^^^^^^^
lib/widgets/player/player_widget.dart:132:64: Error: Member not found: 'none'.
                state?.processingState ?? AudioProcessingState.none;
                                                               ^^^^
lib/widgets/player/player_widget.dart:135:57: Error: Member not found: 'stopped'.
            if (processingState == AudioProcessingState.stopped ||
                                                        ^^^^^^^
lib/widgets/player/player_widget.dart:270:59: Error: Member not found: 'connecting'.
                  processingState == AudioProcessingState.connecting)
                                                          ^^^^^^^^^^
lib/widgets/player/player_widget.dart:421:56: Error: The argument type 'String' can't be assigned to the parameter type 'Map<String, dynamic>'.
 - 'Map' is from 'dart:core'.
    unawaited(AudioService.customAction(SEND_BG_SOUND, name));
                                                       ^
lib/widgets/player/player_widget.dart:422:56: Error: The argument type 'String' can't be assigned to the parameter type 'Map<String, dynamic>'.
 - 'Map' is from 'dart:core'.
    unawaited(AudioService.customAction(PLAY_BG_SOUND, file));
                                                       ^
lib/widgets/player/player_widget.dart:556:26: Error: Member not found: 'AudioService.connect'.
  unawaited(AudioService.connect());
                         ^^^^^^^
lib/widgets/player/player_widget.dart:555:29: Error: The method 'toJson' isn't defined for the class 'MediaItem'.
 - 'MediaItem' is from 'package:audio_service/audio_service.dart' ('../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/audio_service-0.18.3/lib/audio_service.dart').
Try correcting the name to the name of an existing method, or defining a method named 'toJson'.
  var map = {'media': media.toJson()};
                            ^^^^^^
lib/audioplayer/audio_player_service.dart:41:27: Error: Member not found: 'MediaItem.fromJson'.
    mediaItem = MediaItem.fromJson(mediaItemJson);
                          ^^^^^^^^
lib/audioplayer/audio_player_service.dart:235:21: Error: Member not found: 'seekTo'.
        MediaAction.seekTo,
                    ^^^^^^
lib/audioplayer/audio_player_service.dart:251:37: Error: Member not found: 'stopped'.
        return AudioProcessingState.stopped;
                                    ^^^^^^^
lib/audioplayer/audio_player_service.dart:253:37: Error: Member not found: 'connecting'.
        return AudioProcessingState.connecting;
                                    ^^^^^^^^^^
lib/widgets/player/position_indicator_widget.dart:41:27: Error: The getter 'currentPosition' isn't defined for the class 'PlaybackState'.
 - 'PlaybackState' is from 'package:audio_service/audio_service.dart' ('../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/audio_service-0.18.3/lib/audio_service.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'currentPosition'.
            widget.state?.currentPosition?.inMilliseconds?.toDouble() ??
                          ^^^^^^^^^^^^^^^
lib/widgets/player/position_indicator_widget.dart:87:47: Error: The getter 'currentPosition' isn't defined for the class 'PlaybackState'.
 - 'PlaybackState' is from 'package:audio_service/audio_service.dart' ('../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/audio_service-0.18.3/lib/audio_service.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'currentPosition'.
                                widget.state?.currentPosition?.inMilliseconds ??
                                              ^^^^^^^^^^^^^^^
lib/widgets/player/background_sounds_sheet_widget.dart:72:54: Error: The argument type 'String' can't be assigned to the parameter type 'Map<String, dynamic>'.
 - 'Map' is from 'dart:core'.
      await AudioService.customAction(INIT_BG_SOUND, '');
                                                     ^
lib/widgets/player/background_sounds_sheet_widget.dart:267:66: Error: The argument type 'String' can't be assigned to the parameter type 'Map<String, dynamic>'.
 - 'Map' is from 'dart:core'.
            return AudioService.customAction(SEND_BG_SOUND, item.name);
                                                                 ^
lib/widgets/player/background_sounds_sheet_widget.dart:300:46: Error: The argument type 'String' can't be assigned to the parameter type 'Map<String, dynamic>'.
 - 'Map' is from 'dart:core'.
    AudioService.customAction(SEND_BG_SOUND, '');
                                             ^
lib/widgets/player/background_sounds_sheet_widget.dart:301:46: Error: The argument type 'String' can't be assigned to the parameter type 'Map<String, dynamic>'.
 - 'Map' is from 'dart:core'.
    AudioService.customAction(PLAY_BG_SOUND, '');
                                             ^
lib/widgets/player/background_sounds_sheet_widget.dart:347:57: Error: The argument type 'double' can't be assigned to the parameter type 'Map<String, dynamic>'.
 - 'Map' is from 'dart:core'.
                                SET_BG_SOUND_VOL, value / 100);
                                                        ^


FAILURE: Build failed with an exception.

* Where:
Script '/home/paul/snap/flutter/common/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1102

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/home/paul/snap/flutter/common/flutter/bin/flutter'' finished with non-zero exit value 1
</code>
</pre>
</details>

So I guess it would need a deeper look into how to migrate to the 0.18 API of the audio_service package?
Do you have any hint or idea how to solve these issues?

I put up a fork with the described changes here: https://github.com/paulgoetze/medito-app (latest commit on the develop branch, but I was seeing the same issue on master).

I also checked in the `pubspec.lock` file for debugging reasons. I saw it was .gitignored in an earlier commit - 
I was wondering what the reason for that might be? It seems in the Dart guides it's recommended for apps to check in the lock file, too: https://dart.dev/guides/libraries/private-files#pubspeclock

Please let me know if you need further details and how I can help to fix the failing build.

**Comment by scouech** [comment]
@paulgoetze finally looking at this. Will be part of the next major app release. Closing this for now.
Cheers
